### ISSUE TITLE
Sprint Week 1 (05/07 - 09/07)

### ISSUE THREAD

**Issue by SeifShalan** [KhaledSoliman/openlane-cloud#3]
### Backend
- [x] Redis
- [x] Winston logger
- [x] Scheduling Service
- [x] Dashboard Service 
- [x] Authentication Middleware
- [x] Notification Service (Email)

### Frontend
- [x] Login
- [x] Registration
- [x] Reset Password
- [x] Authentication error handling
- [x] Dashboard Template
- [x] Landing Page
- [x] Job Submission Interface

**Comment by KhaledSoliman** [comment]
Landing page, footer and header sections

**Comment by KhaledSoliman** [comment]
Loading state

**Comment by KhaledSoliman** [comment]
Remember me
